/**
 * 落地页「支持的模型」展示清单。
 * `why` 只写能力好处（见 .cursor/rules/model-copy-benefits-only.mdc）。
 */

export type ShowcaseKind = "chat" | "vision" | "image" | "voice" | "video" | "audio";

export type ShowcaseRegion = "foreign" | "domestic";

export type ShowcaseModel = {
  id: string;
  label: string;
  brand: string;
  kind: ShowcaseKind;
  why: string;
  /** Optional English blurb when locale is not zh* */
  whyEn?: string;
  labelEn?: string;
  brandEn?: string;
  model?: string;
};

/** Global / overseas labs first in the landing panel. */
const FOREIGN_BRANDS = new Set([
  "OpenAI",
  "Anthropic",
  "Google",
  "xAI",
  "Midjourney",
  "Black Forest Labs",
  "Stability",
  "ElevenLabs",
  "Cartesia",
  "Inworld",
  "Deepgram",
  "Runway",
  "Suno",
]);

export function showcaseRegion(model: Pick<ShowcaseModel, "brand">): ShowcaseRegion {
  return FOREIGN_BRANDS.has(model.brand) ? "foreign" : "domestic";
}

export const SHOWCASE_KIND_LABEL: Record<ShowcaseKind, string> = {
  chat: "对话",
  vision: "看图",
  image: "出图",
  voice: "语音",
  video: "视频",
  audio: "配乐",
};

/** 本站当前支持的模型（展示用，与运行时选模目录对齐） */
export const SHOWCASE_MODELS: ShowcaseModel[] = [
  // —— 对话 ——
  {
    id: "qwen3.8-max",
    label: "千问 3.8 Max",
    brand: "通义千问",
    labelEn: "Qwen 3.8 Max",
    brandEn: "Tongyi Qwen",
    kind: "chat",
    why: "中文客服、详情页和国内店话术更稳。",
    whyEn: "Steady Chinese support, PDPs, and domestic shop scripts.",
    model: "qwen3.8-max",
  },
  {
    id: "doubao-seed-2-1-pro",
    label: "豆包 Seed 2.1 Pro",
    brand: "豆包",
    labelEn: "Doubao Seed 2.1 Pro",
    brandEn: "Doubao",
    kind: "chat",
    why: "国内客服与短内容表达自然。",
    whyEn: "Natural domestic support and short-form copy.",
    model: "doubao-seed-2-1-pro-260628",
  },
  {
    id: "deepseek-v4-pro",
    label: "DeepSeek V4 Pro",
    brand: "DeepSeek",
    kind: "chat",
    why: "代码、推理与英文刊登更强。",
    whyEn: "Stronger coding, reasoning, and English listings.",
    model: "deepseek-v4-pro",
  },
  {
    id: "kimi-k2.6",
    label: "Kimi K2.6",
    brand: "Kimi",
    kind: "chat",
    why: "长合同、长文档上下文更长。",
    whyEn: "Longer context for contracts and long documents.",
    model: "kimi-k2.6",
  },
  {
    id: "ernie-5.0",
    label: "文心 ERNIE 5.0",
    brand: "百度千帆",
    labelEn: "ERNIE 5.0",
    brandEn: "Baidu Qianfan",
    kind: "chat",
    why: "中文理解、推理与长文本更强。",
    whyEn: "Stronger Chinese understanding, reasoning, and long text.",
    model: "ernie-5.0-thinking-preview",
  },
  {
    id: "glm-5.2",
    label: "GLM-5.2",
    brand: "智谱",
    labelEn: "GLM-5.2",
    brandEn: "Zhipu",
    kind: "chat",
    why: "中文写作、分析与多模态理解均衡。",
    whyEn: "Balanced Chinese writing, analysis, and multimodal understanding.",
    model: "glm-5.2",
  },
  {
    id: "gpt-5.6-sol",
    label: "GPT-5.6 Sol",
    brand: "OpenAI",
    kind: "chat",
    why: "复杂推理、代码与跨境任务表现突出。",
    whyEn: "Strong complex reasoning, code, and cross-border tasks.",
    model: "gpt-5.6-sol",
  },
  {
    id: "claude-sonnet",
    label: "Claude Sonnet",
    brand: "Anthropic",
    kind: "chat",
    why: "长文本、合同与代码审查表达稳妥。",
    whyEn: "Steady long-form, contracts, and code review.",
    model: "claude-sonnet-4-20250514",
  },
  {
    id: "claude-fable-5",
    label: "Claude Fable 5",
    brand: "Anthropic",
    kind: "chat",
    why: "长文写作与细致改稿质量高。",
    whyEn: "High-quality long writing and careful revisions.",
    model: "claude-fable-5",
  },
  {
    id: "gemini-3.1-pro",
    label: "Gemini 3.1 Pro",
    brand: "Google",
    kind: "chat",
    why: "更强长上下文与多模态综合能力。",
    whyEn: "Stronger long context and multimodal synthesis.",
    model: "gemini-3.1-pro-preview",
  },
  {
    id: "gemini-2.5-pro",
    label: "Gemini 2.5 Pro",
    brand: "Google",
    kind: "chat",
    why: "长上下文、多语言与复杂分析强。",
    whyEn: "Strong long context, multilingual, and complex analysis.",
    model: "gemini-2.5-pro",
  },
  {
    id: "grok-3",
    label: "Grok 3",
    brand: "xAI",
    kind: "chat",
    why: "热点追踪与即时向对话。",
    whyEn: "Timely chat for trends and fast back-and-forth.",
    model: "grok-3",
  },
  {
    id: "hy3",
    label: "混元 Hy3",
    brand: "腾讯混元",
    labelEn: "Hunyuan Hy3",
    brandEn: "Tencent Hunyuan",
    kind: "chat",
    why: "国内中文对话稳，客服与通用任务好用。",
    whyEn: "Steady Chinese chat for support and general tasks.",
    model: "hy3",
  },
  {
    id: "kimi-k3",
    label: "Kimi K3",
    brand: "Kimi",
    kind: "chat",
    why: "更长上下文，合同与代码问答更强。",
    whyEn: "Longer context for contracts and coding Q and A.",
    model: "kimi-k3",
  },
  {
    id: "glm-5.3",
    label: "GLM-5.3",
    brand: "智谱",
    labelEn: "GLM-5.3",
    brandEn: "Zhipu",
    kind: "chat",
    why: "中文写作、分析与多模态理解更均衡。",
    whyEn: "More balanced Chinese writing, analysis, and multimodal understanding.",
    model: "glm-5.3",
  },
  {
    id: "minimax-m3",
    label: "MiniMax M3",
    brand: "MiniMax",
    kind: "chat",
    why: "中文表达自然，适合客服与内容草稿。",
    whyEn: "Natural Chinese for support and content drafts.",
    model: "minimax-m3",
  },
  {
    id: "qwen3.5-plus",
    label: "千问 3.5 Plus",
    brand: "通义千问",
    labelEn: "Qwen 3.5 Plus",
    brandEn: "Tongyi Qwen",
    kind: "chat",
    why: "经 TokenHub 补货的千问档，日常中文任务稳。",
    whyEn: "Qwen tier via TokenHub for steady everyday Chinese tasks.",
    model: "qwen3.5-plus",
  },
  {
    id: "youtu-vita",
    label: "Youtu Vita",
    brand: "腾讯优图",
    labelEn: "Youtu Vita",
    brandEn: "Tencent Youtu",
    kind: "chat",
    why: "腾讯侧对话能力，适合国内业务话术。",
    whyEn: "Tencent-side chat suited to domestic business scripts.",
    model: "youtu-vita",
  },

  // —— 看图 ——
  {
    id: "qwen-vl",
    label: "千问看图",
    brand: "通义千问",
    labelEn: "Qwen Vision",
    brandEn: "Tongyi Qwen",
    kind: "vision",
    why: "读合同、发票与商品主图。",
    whyEn: "Read contracts, invoices, and product hero images.",
    model: "qwen-vl-plus",
  },
  {
    id: "hy-vision",
    label: "混元看图 2.0",
    brand: "腾讯混元",
    labelEn: "Hunyuan Vision 2.0",
    brandEn: "Tencent Hunyuan",
    kind: "vision",
    why: "发票、合同与商品图识读备选。",
    whyEn: "Backup for invoices, contracts, and product photos.",
    model: "hy-vision-2.0-instruct",
  },
  {
    id: "glm-5v-turbo",
    label: "GLM-5V Turbo",
    brand: "智谱",
    labelEn: "GLM-5V Turbo",
    brandEn: "Zhipu",
    kind: "vision",
    why: "图文理解快，适合看图分析。",
    whyEn: "Fast image-text understanding for visual analysis.",
    model: "glm-5v-turbo",
  },

  // —— 出图 ——
  {
    id: "wanx-v1",
    label: "万相标准",
    brand: "通义万相",
    labelEn: "Wanxiang Standard",
    brandEn: "Tongyi Wanxiang",
    kind: "image",
    why: "电商主图、海报出图稳，支持参考图。",
    whyEn: "Steady ecommerce heroes and posters; supports reference images.",
    model: "wanx-v1",
  },
  {
    id: "wanx-v1-hq",
    label: "万相高质量",
    brand: "通义万相",
    labelEn: "Wanxiang HQ",
    brandEn: "Tongyi Wanxiang",
    kind: "image",
    why: "更高清晰度，适合 2K/4K 成品。",
    whyEn: "Higher clarity for 2K/4K finals.",
    model: "wanx-v1",
  },
  {
    id: "jimeng-t2i",
    label: "即梦 4.0",
    brand: "即梦",
    labelEn: "Jimeng 4.0",
    brandEn: "Jimeng",
    kind: "image",
    why: "国内创意与电商氛围感更强。",
    whyEn: "Stronger domestic creative and ecommerce vibe.",
    model: "jimeng_t2i_v40",
  },
  {
    id: "hy-image-v3",
    label: "混元图像 V3",
    brand: "腾讯混元",
    labelEn: "Hunyuan Image V3",
    brandEn: "Tencent Hunyuan",
    kind: "image",
    why: "国内主图与海报风格稳，经 TokenHub 可调。",
    whyEn: "Steady domestic heroes and posters via TokenHub.",
    model: "hy-image-v3",
  },
  {
    id: "seedream-image-v5",
    label: "Seedream 5.0",
    brand: "即梦 / Seedream",
    labelEn: "Seedream 5.0",
    brandEn: "Jimeng / Seedream",
    kind: "image",
    why: "高质量创意出图，适合品牌视觉试稿。",
    whyEn: "High-quality creative stills for brand visual drafts.",
    model: "seedream-image-v5.0-pro",
  },
  {
    id: "midjourney",
    label: "Midjourney",
    brand: "Midjourney",
    kind: "image",
    why: "艺术风格与创意构图突出。",
    whyEn: "Standout art style and creative composition.",
    model: "midjourney",
  },
  {
    id: "flux-schnell",
    label: "FLUX Schnell",
    brand: "Black Forest Labs",
    kind: "image",
    why: "开源快速出图，迭代试稿快。",
    whyEn: "Open fast image gen for quick drafts.",
    model: "black-forest-labs/flux-schnell",
  },
  {
    id: "sdxl",
    label: "SDXL",
    brand: "Stability",
    kind: "image",
    why: "开源可控，适合批量与风格实验。",
    whyEn: "Open and controllable for batches and style tests.",
    model: "stability-ai/sdxl",
  },
  {
    id: "hy-3d",
    label: "混元 3D",
    brand: "腾讯混元",
    labelEn: "Hunyuan 3D",
    brandEn: "Tencent Hunyuan",
    kind: "image",
    why: "商品与道具三维资产生成，适合陈列与包装预览。",
    whyEn: "3D assets for product display and packaging previews.",
    model: "hy-3d-3.1",
  },
  {
    id: "tripo-3d",
    label: "Tripo 3D",
    brand: "Tripo",
    kind: "image",
    why: "快速三维建模与绑定，适合电商与互动预览。",
    whyEn: "Fast 3D modeling and rigging for ecommerce previews.",
    model: "tripo-3d-3.1",
  },

  // —— 语音 ——
  {
    id: "qwen3-tts-vc",
    label: "千问 Qwen3-TTS 克隆",
    brand: "通义千问",
    labelEn: "Qwen3-TTS Clone",
    brandEn: "Tongyi Qwen",
    kind: "voice",
    why: "中文真克隆，口播更像本人。",
    whyEn: "True Chinese voice clone for natural narration.",
    model: "qwen3-tts-vc-2026-01-22",
  },
  {
    id: "cosyvoice-v2",
    label: "千问 CosyVoice",
    brand: "通义千问",
    labelEn: "Qwen CosyVoice",
    brandEn: "Tongyi Qwen",
    kind: "voice",
    why: "通用中文音色，草稿试听快。",
    whyEn: "General Chinese voices for quick drafts.",
    model: "cosyvoice-v2",
  },
  {
    id: "minimax-speech-2.8-hd",
    label: "MiniMax speech-2.8-hd",
    brand: "MiniMax",
    kind: "voice",
    why: "海螺高清，中英口播质感强。",
    whyEn: "HD Chinese/English narration with strong presence.",
    model: "speech-2.8-hd",
  },
  {
    id: "minimax-speech-2.6-hd",
    label: "MiniMax speech-2.6-hd",
    brand: "MiniMax",
    kind: "voice",
    why: "稳定高清档，性价比好。",
    whyEn: "Stable HD tier with good value.",
    model: "speech-2.6-hd",
  },
  {
    id: "minimax-speech-2.6-turbo",
    label: "MiniMax speech-2.6-turbo",
    brand: "MiniMax",
    kind: "voice",
    why: "更快更省，适合多语种量产。",
    whyEn: "Faster and cheaper for multilingual volume.",
    model: "speech-2.6-turbo",
  },
  {
    id: "hy-asr",
    label: "混元 ASR",
    brand: "腾讯混元",
    labelEn: "Hunyuan ASR",
    brandEn: "Tencent Hunyuan",
    kind: "voice",
    why: "中文会议与口播转写备选。",
    whyEn: "Chinese meeting and narration transcription backup.",
    model: "hy-asr-3.0-preview",
  },
  {
    id: "wand-asr",
    label: "Wand ASR",
    brand: "TokenHub",
    kind: "voice",
    why: "经 TokenHub 的语音转写通道。",
    whyEn: "Speech-to-text channel via TokenHub.",
    model: "wand-asr-v1",
  },
  {
    id: "elevenlabs-multilingual",
    label: "ElevenLabs Multilingual",
    brand: "ElevenLabs",
    kind: "voice",
    why: "英文精品旁白与多语种质感强。",
    whyEn: "Premium English VO and strong multilingual tone.",
    model: "eleven_multilingual_v2",
  },
  {
    id: "openai-tts-hd",
    label: "OpenAI TTS-HD",
    brand: "OpenAI",
    kind: "voice",
    why: "英文旁白清晰稳定。",
    whyEn: "Clear, stable English narration.",
    model: "tts-1-hd",
  },
  {
    id: "fish-s2-pro",
    label: "Fish Audio S2 Pro",
    brand: "Fish Audio",
    kind: "voice",
    why: "中英性价比高，支持真克隆。",
    whyEn: "Strong CN/EN value with true cloning.",
    model: "s2-pro",
  },
  {
    id: "cartesia-sonic",
    label: "Cartesia Sonic",
    brand: "Cartesia",
    kind: "voice",
    why: "英文低延迟，适合实时播报。",
    whyEn: "Low-latency English for live announcements.",
    model: "sonic-3",
  },
  {
    id: "inworld-tts",
    label: "Inworld TTS",
    brand: "Inworld",
    kind: "voice",
    why: "英文实时对话音质高。",
    whyEn: "High-quality English realtime dialogue voice.",
    model: "inworld-tts-1.5-max",
  },
  {
    id: "deepgram-aura",
    label: "Deepgram Aura",
    brand: "Deepgram",
    kind: "voice",
    why: "语音客服场景延迟低。",
    whyEn: "Low latency for voice support scenarios.",
    model: "aura",
  },
  {
    id: "whisper",
    label: "Whisper",
    brand: "OpenAI",
    kind: "voice",
    why: "会议与口播转写准确。",
    whyEn: "Accurate meeting and narration transcription.",
    model: "whisper-1",
  },

  // —— 视频 ——
  {
    id: "runway-gen3",
    label: "Runway Gen-3",
    brand: "Runway",
    kind: "video",
    why: "文生/图生短视频成片稳定。",
    whyEn: "Stable text/image-to-short-video finals.",
    model: "gen3",
  },
  {
    id: "kling-video",
    label: "可灵 Kling",
    brand: "可灵",
    labelEn: "Kling",
    brandEn: "Kling",
    kind: "video",
    why: "中文镜头理解好，适合短片成片。",
    whyEn: "Strong Chinese shot understanding for short films.",
    model: "kling-v1",
  },
  {
    id: "kling-video-v3",
    label: "可灵 Kling V3",
    brand: "可灵",
    labelEn: "Kling V3",
    brandEn: "Kling",
    kind: "video",
    why: "TokenHub 可调用的可灵新版，运镜更稳。",
    whyEn: "Newer Kling via TokenHub with steadier camera moves.",
    model: "kling-video-v3",
  },
  {
    id: "hy-video",
    label: "混元视频",
    brand: "腾讯混元",
    labelEn: "Hunyuan Video",
    brandEn: "Tencent Hunyuan",
    kind: "video",
    why: "国内短片与运镜生成，经 TokenHub 可调。",
    whyEn: "Domestic short-form and camera generation via TokenHub.",
    model: "hy-video-v1.5",
  },
  {
    id: "minimax-video",
    label: "MiniMax Video",
    brand: "MiniMax",
    kind: "video",
    why: "海螺视频成片，适合广告与口播短片。",
    whyEn: "Hailuo video finals for ads and spoken shorts.",
    model: "minimax-video-v2.3",
  },
  {
    id: "vidu-video-q3",
    label: "Vidu Q3",
    brand: "Vidu",
    kind: "video",
    why: "文生/图生短视频迭代快。",
    whyEn: "Fast text/image-to-video iteration.",
    model: "vidu-video-q3",
  },
  {
    id: "pixverse-video",
    label: "PixVerse V6",
    brand: "PixVerse",
    kind: "video",
    why: "创意运镜与特效向短片。",
    whyEn: "Creative camera moves and effects-led shorts.",
    model: "pixverse-video-v6.0",
  },
  {
    id: "jimeng-video",
    label: "即梦视频",
    brand: "即梦",
    labelEn: "Jimeng Video",
    brandEn: "Jimeng",
    kind: "video",
    why: "国内短视频创意与运镜风格鲜明。",
    whyEn: "Distinct domestic short-video creative and camera moves.",
    model: "jimeng_t2v_v30",
  },

  // —— 配乐 ——
  {
    id: "suno",
    label: "Suno",
    brand: "Suno",
    kind: "audio",
    why: "短视频 BGM 与片头配乐一键成曲。",
    whyEn: "One-click BGM and intro music for short video.",
    model: "suno",
  },
  {
    id: "minimax-music",
    label: "MiniMax Music",
    brand: "MiniMax",
    kind: "audio",
    why: "短视频 BGM 与片头配乐备选。",
    whyEn: "Backup BGM and intro music for short video.",
    model: "minimax-music-v3.0",
  },
];
